<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Bibliotecas" data-toc-modified-id="Bibliotecas-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Bibliotecas</a></span></li><li><span><a href="#Importação-dos-dados" data-toc-modified-id="Importação-dos-dados-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Importação dos dados</a></span></li></ul></div>

# Bibliotecas

In [2]:
import os
import pandas as pd

import math

import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
import numpy as np

# Importação dos dados

In [3]:
d_path = os.getcwd()
df = pd.read_csv(d_path+"\\estacoes.csv"
                     ,sep = ','
                     ,decimal='.'
                      )

In [4]:
df

    id_estacao  id_localidade  latitude      long             bairro
0          174            225 -22.88200 -43.12300             CENTRO
1          175            198 -22.90500 -43.12100               INGÁ
2          176            193 -22.90700 -43.06700             MACEIÓ
3          177            239 -22.86900 -43.07000            FONSECA
4          178            246 -22.86200 -43.09900            BARRETO
5          179            232 -22.87700 -43.04900      SANTA BÁRBARA
6          180            227 -22.88100 -43.03000        MARIA PAULA
7          181            147 -22.95400 -43.02800             ITAIPU
8          182            195 -22.90600 -43.05300             ITAIPU
9          183            192 -22.90800 -42.98500   VÁRZEA DAS MOÇAS
10         184            166 -22.93200 -43.11600           JURUJUBA
11         185            157 -22.94200 -43.05700        PIRATININGA
12         186            162 -22.93400 -43.09800           CHARITAS
13         187            171 -22.92900 -43.06400        PIRATININGA
14         188            150 -22.95100 -43.09200        PIRATININGA
15         189            223 -22.88300 -43.08300            FONSECA
16         500            211 -22.89413 -43.10946   BAIRRO DE FÁTIMA
17         501            244 -22.86396 -43.09919            BARRETO
18         502            221 -22.88560 -43.10486       SÃO LOURENÇO
19         503            228 -22.88042 -43.07673          BALDEADOR
20         504            224 -22.88261 -43.06575           CARAMUJO
21         505            189 -22.91232 -43.10239      SÃO FRANCISCO
22         506            237 -22.87304 -43.09037          ENGENHOCA
23         507            160 -22.93488 -43.00772    ENGENHO DO MATO
24         508            194 -22.90697 -43.07101   LARGO DA BATALHA
25         509            142 -22.96146 -43.03310             ITAIPU
26         510            163 -22.93375 -43.10939  BAÍA DE GUANABARA
27         511            187 -22.91361 -43.07244      SÃO FRANCISCO
28         512            158 -22.93688 -43.03176          MARAVISTA
29         513            226 -22.88196 -43.03137          PENDOTIBA
30         514            222 -22.88437 -43.12575      PONTA D'AREIA
31         515            215 -22.89139 -43.08586            CUBANGO
32         516            236 -22.87305 -43.06890          BALDEADOR
33         517            203 -22.89955 -43.11825               INGÁ
34         518            197 -22.90558 -43.12609               INGÁ
35         519            208 -22.89656 -43.10201         PÉ PEQUENO
36         520            161 -22.93468 -43.07041        PIRATININGA
37         521            148 -22.95102 -43.09167        PIRATININGA
38         522            159 -22.93495 -43.09957           CHARITAS
39         523            214 -22.89142 -42.99720        RIO DO OURO
40         524            233 -22.87634 -43.04640      SANTA BÁRBARA
41         525            184 -22.91651 -43.09124      SÃO FRANCISCO
42         526            205 -22.89716 -43.05958               SAPÊ
43         527            245 -22.86352 -43.08443     TENENTE JARDIM
44         528            200 -22.90290 -43.08674         SANTA ROSA
45         529            190 -22.91015 -42.98538   VÁRZEA DAS MOÇAS

In [5]:
quantidade_estacoes = len(df["id_estacao"])
latitude = df["latitude"]
longitude = df["long"]

In [6]:
M = np.zeros((quantidade_estacoes,quantidade_estacoes))
lat, lon = [min(latitude),min(longitude)]
valor_andar_lat = (max(latitude)-min(latitude))/quantidade_estacoes
valor_andar_lon = (max(longitude)-min(longitude))/quantidade_estacoes
latitude = df["latitude"]
longitude = df["long"]
id_medidor = df["id_estacao"]
for y in range(quantidade_estacoes): #Percorrendo longitudes
    for x in range(quantidade_estacoes): #Percorrendo latitudes
        dmin = math.hypot(lat-valor_andar_lat, lon-valor_andar_lon) #Norma euclidiana, distância mínima entre máximo de x e máximo de y
        j = -1
        for i in range(quantidade_estacoes):
            d = math.hypot(latitude[i]-lat-(x*valor_andar_lat), longitude[i]-lon-(y*valor_andar_lon)) #Norma euclidiana, distância mínima entre a diferença do valor a cada ponto do loop
            if d < dmin: # Se distancia for menor que a distancia minima estipulada
                dmin = d # distancia minima recebe novo valor
                j = id_medidor[i] #  (Colocar ID_medidor)
        M[x][y] = j

In [7]:
M

array([[184., 184., 510., ..., 507., 507., 507.],
       [184., 184., 184., ..., 507., 507., 507.],
       [184., 184., 184., ..., 507., 507., 507.],
       ...,
       [174., 174., 174., ..., 523., 523., 523.],
       [174., 174., 174., ..., 523., 523., 523.],
       [174., 174., 174., ..., 523., 523., 523.]])

In [8]:
data_frame = pd.DataFrame(M)

In [9]:
data_frame

,0,1,2,3,4,5,6,7,8,9,...,36,37,38,39,40,41,42,43,44,45
0,184.0,184.0,510.0,188.0,188.0,188.0,188.0,188.0,188.0,188.0,...,181.0,181.0,181.0,181.0,181.0,507.0,507.0,507.0,507.0,507.0
1,184.0,184.0,184.0,188.0,188.0,188.0,188.0,188.0,188.0,188.0,...,181.0,181.0,181.0,181.0,507.0,507.0,507.0,507.0,507.0,507.0
2,184.0,184.0,184.0,510.0,188.0,188.0,188.0,188.0,188.0,188.0,...,181.0,181.0,181.0,181.0,507.0,507.0,507.0,507.0,507.0,507.0
3,184.0,184.0,184.0,510.0,510.0,188.0,188.0,188.0,188.0,188.0,...,181.0,181.0,181.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
4,184.0,184.0,184.0,510.0,510.0,188.0,188.0,188.0,188.0,188.0,...,181.0,181.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
5,184.0,184.0,184.0,510.0,510.0,510.0,188.0,188.0,188.0,188.0,...,181.0,181.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
6,184.0,184.0,184.0,184.0,510.0,510.0,510.0,188.0,188.0,188.0,...,181.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
7,184.0,184.0,184.0,184.0,510.0,510.0,510.0,522.0,188.0,188.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
8,184.0,184.0,184.0,184.0,510.0,510.0,510.0,522.0,522.0,522.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
9,184.0,184.0,184.0,184.0,510.0,510.0,510.0,522.0,522.0,522.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
10,184.0,184.0,184.0,184.0,510.0,510.0,510.0,522.0,522.0,522.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
11,184.0,184.0,184.0,184.0,510.0,510.0,510.0,522.0,522.0,522.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
12,184.0,184.0,184.0,184.0,184.0,510.0,510.0,522.0,522.0,522.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
13,184.0,184.0,184.0,184.0,184.0,510.0,510.0,510.0,522.0,186.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
14,184.0,184.0,184.0,184.0,184.0,510.0,510.0,510.0,522.0,186.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
15,184.0,184.0,184.0,184.0,184.0,510.0,510.0,510.0,186.0,186.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,529.0
16,184.0,184.0,184.0,184.0,184.0,510.0,510.0,510.0,186.0,186.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,529.0,529.0
17,184.0,184.0,184.0,184.0,184.0,184.0,510.0,510.0,186.0,186.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,529.0,529.0
18,184.0,184.0,184.0,184.0,184.0,184.0,510.0,505.0,505.0,525.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,529.0,529.0,529.0
19,518.0,184.0,184.0,184.0,184.0,505.0,505.0,505.0,505.0,525.0,...,507.0,507.0,507.0,507.0,507.0,507.0,529.0,529.0,529.0,529.0
20,518.0,518.0,175.0,184.0,505.0,505.0,505.0,505.0,505.0,505.0,...,507.0,507.0,507.0,507.0,507.0,529.0,529.0,529.0,529.0,529.0
21,518.0,518.0,175.0,175.0,505.0,505.0,505.0,505.0,505.0,505.0,...,507.0,507.0,507.0,507.0,529.0,529.0,529.0,529.0,529.0,529.0
22,518.0,518.0,175.0,175.0,175.0,505.0,505.0,505.0,505.0,505.0,...,507.0,507.0,507.0,507.0,529.0,529.0,529.0,529.0,529.0,529.0
23,518.0,518.0,175.0,175.0,175.0,505.0,505.0,505.0,505.0,505.0,...,507.0,507.0,507.0,529.0,529.0,529.0,529.0,529.0,529.0,529.0
24,518.0,175.0,175.0,175.0,175.0,505.0,505.0,505.0,505.0,505.0,...,523.0,523.0,523.0,523.0,529.0,529.0,529.0,529.0,529.0,529.0
25,518.0,175.0,175.0,175.0,175.0,505.0,505.0,505.0,505.0,505.0,...,523.0,523.0,523.0,523.0,523.0,529.0,529.0,183.0,183.0,183.0
26,518.0,175.0,175.0,175.0,175.0,517.0,505.0,505.0,505.0,505.0,...,523.0,523.0,523.0,523.0,523.0,523.0,183.0,183.0,183.0,183.0
27,518.0,175.0,175.0,517.0,517.0,517.0,519.0,519.0,519.0,519.0,...,523.0,523.0,523.0,523.0,523.0,523.0,523.0,183.0,183.0,183.0
28,518.0,175.0,517.0,517.0,517.0,500.0,500.0,519.0,519.0,519.0,...,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,183.0,183.0
29,518.0,517.0,517.0,517.0,517.0,500.0,500.0,519.0,519.0,519.0,...,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,183.0
30,517.0,517.0,517.0,517.0,500.0,500.0,500.0,519.0,519.0,519.0,...,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
31,517.0,517.0,517.0,517.0,500.0,500.0,500.0,519.0,519.0,519.0,...,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
32,514.0,514.0,517.0,517.0,500.0,500.0,500.0,519.0,519.0,519.0,...,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
33,514.0,514.0,514.0,500.0,500.0,500.0,500.0,502.0,502.0,519.0,...,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
34,514.0,514.0,174.0,174.0,500.0,500.0,502.0,502.0,502.0,502.0,...,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
35,514.0,514.0,174.0,174.0,502.0,502.0,502.0,502.0,502.0,502.0,...,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
36,514.0,174.0,174.0,174.0,502.0,502.0,502.0,502.0,502.0,502.0,...,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
37,514.0,174.0,174.0,174.0,174.0,502.0,502.0,502.0,502.0,502.0,...,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
38,174.0,174.0,174.0,174.0,174.0,502.0,502.0,502.0,502.0,502.0,...,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
39,174.0,174.0,174.0,174.0,174.0,502.0,502.0,502.0,502.0,506.0,...,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
40,174.0,174.0,174.0,174.0,174.0,502.0,502.0,502.0,502.0,506.0,...,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
41,174.0,174.0,174.0,174.0,174.0,502.0,501.0,501.0,501.0,506.0,...,180.0,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
42,174.0,174.0,174.0,174.0,174.0,501.0,501.0,501.0,501.0,501.0,...,180.0,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
43,174.0,174.0,174.0,174.0,501.0,501.0,501.0,501.0,501.0,501.0,...,180.0,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
44,174.0,174.0,174.0,174.0,501.0,501.0,501.0,501.0,501.0,501.0,...,180.0,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
45,174.0,174.0,174.0,501.0,501.0,501.0,501.0,501.0,501.0,501.0,...,180.0,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0

In [10]:
lat_df = []
lon_df = []
lat, lon = [min(latitude),min(longitude)]
valor_andar_lat = (max(latitude)-min(latitude))/quantidade_estacoes
valor_andar_lon = (max(longitude)-min(longitude))/quantidade_estacoes
for i in range(quantidade_estacoes):
    lat_df.append(lat+(i*valor_andar_lat))
    lon_df.append(lon+(i*valor_andar_lon))

In [11]:
lat_df

[-22.96146,
 -22.959297826086956,
 -22.95713565217391,
 -22.954973478260868,
 -22.952811304347826,
 -22.95064913043478,
 -22.948486956521737,
 -22.946324782608695,
 -22.944162608695652,
 -22.942000434782607,
 -22.939838260869564,
 -22.93767608695652,
 -22.935513913043476,
 -22.933351739130433,
 -22.93118956521739,
 -22.929027391304345,
 -22.926865217391303,
 -22.92470304347826,
 -22.922540869565218,
 -22.920378695652172,
 -22.91821652173913,
 -22.916054347826087,
 -22.91389217391304,
 -22.91173,
 -22.909567826086956,
 -22.90740565217391,
 -22.905243478260868,
 -22.903081304347825,
 -22.90091913043478,
 -22.898756956521737,
 -22.896594782608695,
 -22.894432608695652,
 -22.892270434782606,
 -22.890108260869564,
 -22.88794608695652,
 -22.885783913043475,
 -22.883621739130433,
 -22.88145956521739,
 -22.879297391304345,
 -22.877135217391302,
 -22.87497304347826,
 -22.872810869565217,
 -22.87064869565217,
 -22.86848652173913,
 -22.866324347826087,
 -22.86416217391304]

In [12]:
lon_df

[-43.12609,
 -43.12302282608695,
 -43.119955652173914,
 -43.11688847826087,
 -43.11382130434782,
 -43.11075413043478,
 -43.10768695652174,
 -43.104619782608694,
 -43.10155260869565,
 -43.09848543478261,
 -43.095418260869565,
 -43.09235108695652,
 -43.089283913043474,
 -43.086216739130435,
 -43.08314956521739,
 -43.080082391304344,
 -43.077015217391306,
 -43.07394804347826,
 -43.070880869565215,
 -43.06781369565217,
 -43.06474652173913,
 -43.061679347826086,
 -43.05861217391304,
 -43.055544999999995,
 -43.05247782608696,
 -43.04941065217391,
 -43.046343478260866,
 -43.04327630434783,
 -43.04020913043478,
 -43.03714195652174,
 -43.03407478260869,
 -43.03100760869565,
 -43.02794043478261,
 -43.02487326086956,
 -43.02180608695652,
 -43.01873891304348,
 -43.01567173913043,
 -43.01260456521739,
 -43.00953739130435,
 -43.0064702173913,
 -43.00340304347826,
 -43.00033586956522,
 -42.997268695652174,
 -42.99420152173913,
 -42.99113434782608,
 -42.988067173913045]

In [13]:
df_marks = data_frame.copy()
df_marks.columns = lon_df
df_marks = df_marks.rename_axis(columns='longitude')

In [14]:
df_marks["latitude"] = lat_df
df_marks = df_marks.set_index("latitude")

In [15]:
df_marks

longitude,-43.126090,-43.123023,-43.119956,-43.116888,-43.113821,-43.110754,-43.107687,-43.104620,-43.101553,-43.098485,...,-43.015672,-43.012605,-43.009537,-43.006470,-43.003403,-43.000336,-42.997269,-42.994202,-42.991134,-42.988067
latitude,,,,,,,,,,,,,,,,,,,,,
-22.961460,184.0,184.0,510.0,188.0,188.0,188.0,188.0,188.0,188.0,188.0,...,181.0,181.0,181.0,181.0,181.0,507.0,507.0,507.0,507.0,507.0
-22.959298,184.0,184.0,184.0,188.0,188.0,188.0,188.0,188.0,188.0,188.0,...,181.0,181.0,181.0,181.0,507.0,507.0,507.0,507.0,507.0,507.0
-22.957136,184.0,184.0,184.0,510.0,188.0,188.0,188.0,188.0,188.0,188.0,...,181.0,181.0,181.0,181.0,507.0,507.0,507.0,507.0,507.0,507.0
-22.954973,184.0,184.0,184.0,510.0,510.0,188.0,188.0,188.0,188.0,188.0,...,181.0,181.0,181.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
-22.952811,184.0,184.0,184.0,510.0,510.0,188.0,188.0,188.0,188.0,188.0,...,181.0,181.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
-22.950649,184.0,184.0,184.0,510.0,510.0,510.0,188.0,188.0,188.0,188.0,...,181.0,181.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
-22.948487,184.0,184.0,184.0,184.0,510.0,510.0,510.0,188.0,188.0,188.0,...,181.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
-22.946325,184.0,184.0,184.0,184.0,510.0,510.0,510.0,522.0,188.0,188.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
-22.944163,184.0,184.0,184.0,184.0,510.0,510.0,510.0,522.0,522.0,522.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
-22.942000,184.0,184.0,184.0,184.0,510.0,510.0,510.0,522.0,522.0,522.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
-22.939838,184.0,184.0,184.0,184.0,510.0,510.0,510.0,522.0,522.0,522.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
-22.937676,184.0,184.0,184.0,184.0,510.0,510.0,510.0,522.0,522.0,522.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
-22.935514,184.0,184.0,184.0,184.0,184.0,510.0,510.0,522.0,522.0,522.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
-22.933352,184.0,184.0,184.0,184.0,184.0,510.0,510.0,510.0,522.0,186.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
-22.931190,184.0,184.0,184.0,184.0,184.0,510.0,510.0,510.0,522.0,186.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0
-22.929027,184.0,184.0,184.0,184.0,184.0,510.0,510.0,510.0,186.0,186.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,529.0
-22.926865,184.0,184.0,184.0,184.0,184.0,510.0,510.0,510.0,186.0,186.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,529.0,529.0
-22.924703,184.0,184.0,184.0,184.0,184.0,184.0,510.0,510.0,186.0,186.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,507.0,529.0,529.0
-22.922541,184.0,184.0,184.0,184.0,184.0,184.0,510.0,505.0,505.0,525.0,...,507.0,507.0,507.0,507.0,507.0,507.0,507.0,529.0,529.0,529.0
-22.920379,518.0,184.0,184.0,184.0,184.0,505.0,505.0,505.0,505.0,525.0,...,507.0,507.0,507.0,507.0,507.0,507.0,529.0,529.0,529.0,529.0
-22.918217,518.0,518.0,175.0,184.0,505.0,505.0,505.0,505.0,505.0,505.0,...,507.0,507.0,507.0,507.0,507.0,529.0,529.0,529.0,529.0,529.0
-22.916054,518.0,518.0,175.0,175.0,505.0,505.0,505.0,505.0,505.0,505.0,...,507.0,507.0,507.0,507.0,529.0,529.0,529.0,529.0,529.0,529.0
-22.913892,518.0,518.0,175.0,175.0,175.0,505.0,505.0,505.0,505.0,505.0,...,507.0,507.0,507.0,507.0,529.0,529.0,529.0,529.0,529.0,529.0
-22.911730,518.0,518.0,175.0,175.0,175.0,505.0,505.0,505.0,505.0,505.0,...,507.0,507.0,507.0,529.0,529.0,529.0,529.0,529.0,529.0,529.0
-22.909568,518.0,175.0,175.0,175.0,175.0,505.0,505.0,505.0,505.0,505.0,...,523.0,523.0,523.0,523.0,529.0,529.0,529.0,529.0,529.0,529.0
-22.907406,518.0,175.0,175.0,175.0,175.0,505.0,505.0,505.0,505.0,505.0,...,523.0,523.0,523.0,523.0,523.0,529.0,529.0,183.0,183.0,183.0
-22.905243,518.0,175.0,175.0,175.0,175.0,517.0,505.0,505.0,505.0,505.0,...,523.0,523.0,523.0,523.0,523.0,523.0,183.0,183.0,183.0,183.0
-22.903081,518.0,175.0,175.0,517.0,517.0,517.0,519.0,519.0,519.0,519.0,...,523.0,523.0,523.0,523.0,523.0,523.0,523.0,183.0,183.0,183.0
-22.900919,518.0,175.0,517.0,517.0,517.0,500.0,500.0,519.0,519.0,519.0,...,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,183.0,183.0
-22.898757,518.0,517.0,517.0,517.0,517.0,500.0,500.0,519.0,519.0,519.0,...,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,183.0
-22.896595,517.0,517.0,517.0,517.0,500.0,500.0,500.0,519.0,519.0,519.0,...,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.894433,517.0,517.0,517.0,517.0,500.0,500.0,500.0,519.0,519.0,519.0,...,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.892270,514.0,514.0,517.0,517.0,500.0,500.0,500.0,519.0,519.0,519.0,...,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.890108,514.0,514.0,514.0,500.0,500.0,500.0,500.0,502.0,502.0,519.0,...,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.887946,514.0,514.0,174.0,174.0,500.0,500.0,502.0,502.0,502.0,502.0,...,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.885784,514.0,514.0,174.0,174.0,502.0,502.0,502.0,502.0,502.0,502.0,...,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.883622,514.0,174.0,174.0,174.0,502.0,502.0,502.0,502.0,502.0,502.0,...,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.881460,514.0,174.0,174.0,174.0,174.0,502.0,502.0,502.0,502.0,502.0,...,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.879297,174.0,174.0,174.0,174.0,174.0,502.0,502.0,502.0,502.0,502.0,...,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.877135,174.0,174.0,174.0,174.0,174.0,502.0,502.0,502.0,502.0,506.0,...,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.874973,174.0,174.0,174.0,174.0,174.0,502.0,502.0,502.0,502.0,506.0,...,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.872811,174.0,174.0,174.0,174.0,174.0,502.0,501.0,501.0,501.0,506.0,...,180.0,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.870649,174.0,174.0,174.0,174.0,174.0,501.0,501.0,501.0,501.0,501.0,...,180.0,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.868487,174.0,174.0,174.0,174.0,501.0,501.0,501.0,501.0,501.0,501.0,...,180.0,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.866324,174.0,174.0,174.0,174.0,501.0,501.0,501.0,501.0,501.0,501.0,...,180.0,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0
-22.864162,174.0,174.0,174.0,501.0,501.0,501.0,501.0,501.0,501.0,501.0,...,180.0,180.0,180.0,523.0,523.0,523.0,523.0,523.0,523.0,523.0