In [1]:
import pandas as pd
import numpy as np

In [6]:
def Woe_IV_Dis(df, features, target):
    aux = features + [target] 
    
    df = df[aux].copy()
    
    # Empty dataframe
    df_woe_iv = pd.DataFrame({},index=[])
    
    for feature in features:
        df_woe_iv_aux = pd.crosstab(df[feature], df[target], normalize='columns') \
                        .assign(RR=lambda dfx: dfx[1] / dfx[0]) \
                        .assign(WoE=lambda dfx: np.log(dfx[1] / dfx[0])) \
                        .assign(IV=lambda dfx: (dfx['WoE']*(dfx[1]-dfx[0]))) \
                        .assign(IV_total=lambda dfx: np.sum(dfx['IV']))

        df_woe_iv = pd.concat([df_woe_iv, df_woe_iv_aux])
    
    return df_woe_iv

In [2]:
df = pd.read_csv('df_comp2.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4501860 entries, 0 to 4501859
Data columns (total 36 columns):
 #   Column                                     Dtype
---  ------                                     -----
 0   Unnamed: 0                                 int64
 1   n_coord                                    int64
 2   ocorrencia                                 float64
 3   vintequatrohoras                           float64
 4   Altitude_numerica                          float64
 5   Declividade_numerica                       float64
 6   graurisc                                   float64
 7   lon_ocr                                    float64
 8   lat_ocr                                    float64
 9   Orientacao_numerica                        float64
 10  Curv_Vertical_numerica                     float64
 11  Curv_Horizontal_numerica                   float64
 12  Relevo_sombreado_numerico                  float64
 13  Vegetacao_Natural_Dominante                int64
 14  Area_Antropica_Dominante                   int64
 15  legenda_2_Pecuária (pastagens)             int64
 16  Floresta_Ombrofila_Densa                   int64
 17  Formacao_Pioneira                          int64
 18  Floresta_Ombrofila_Densa_Submontana        int64
 19  Influencia_urbana                          int64
 20  Vegetacao_Secundaria                       int64
 21  Argilossolo                                int64
 22  Gleissolo                                  int64
 23  Argilossolo_Vermelho_Amarelo               int64
 24  Gleissolo_Melanico                         int64
 25  Area_Urbana                                int64
 26  Unidades_de_Conservacao_Protecao_Integral  int64
 27  Plano_de_Manejo                            int64
 28  flg_comunidades                            int64
 29  flg_agricola                               int64
 30  flg_exploracao_mineral                     int64
 31  flg_rocha                                  int64
 32  flg_cobertura_vegetal                      int64
 33  flg_afloramento_rochoso                    int64
 34  flg_ocupacao_desordenada                   int64
 35  tempo                                      object
dtypes: float64(11), int64(24), object(1)
memory usage: 1.2+ GB

In [13]:
discretas = ['flg_exploracao_mineral'                     
,'flg_rocha'                                  
,'flg_cobertura_vegetal'                      
,'flg_afloramento_rochoso'                    
,'flg_ocupacao_desordenada'  ]

continuas = ['vintequatrohoras'         
,'Altitude_numerica'        
,'Declividade_numerica'     
,'graurisc'                 
,'lon_ocr'                  
,'lat_ocr'                  
,'Orientacao_numerica'      
,'Curv_Vertical_numerica'   
,'Curv_Horizontal_numerica' 
,'Relevo_sombreado_numerico']

In [14]:
Woe_IV_Dis(df, discretas, 'ocorrencia')

/home/pdpa-chuvas/miniconda3/envs/tf/lib/python3.8/site-packages/pandas/core/arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

ocorrencia       0.0       1.0        RR       WoE            IV  IV_total
0           0.998405  0.998856  1.000452  0.000451  2.035166e-07  0.000150
1           0.001595  0.001144  0.717352 -0.332189  1.497570e-04  0.000150
0           1.000000  1.000000  1.000000  0.000000  0.000000e+00  0.000000
0           0.508371  0.927918  1.825275  0.601730  2.524537e-01  1.057946
1           0.491629  0.072082  0.146620 -1.919914  8.054924e-01  1.057946
0           0.979581  1.000000  1.020844  0.020630  4.212361e-04       inf
1           0.020419  0.000000  0.000000      -inf           inf       inf
0           0.977037  0.956522  0.979002 -0.021221  4.353746e-04  0.013533
1           0.022963  0.043478  1.893444  0.638398  1.309720e-02  0.013533

In [15]:
def Woe_IV_cont(df, features, target):
    
    aux = features + [target] 
    
    df = df[aux].copy()
    
    # Empty dataframe
    df_woe_iv = pd.DataFrame({},index=[])
    
    # Number of rows with target = 1
    _t1 = sum(df[target])
    # Number of rows with target = 0
    _t0 =  len(df[target]) - _t1
    
    # Percentile of continuous variables
    _quantile = df.iloc[:, :-1].quantile([.1, .2, .3, .4, .5, .6, .7, .8, .9], axis = 0)
    
    
    for _column in _quantile.columns:
   
        # Non-duplicated quantile limit values
        list_aux = _quantile[[_column]].drop_duplicates().to_numpy()
    
        _tiv = 0
        
        for q in range(len(list_aux)):
            
            
            if q>0:
                location = df[(df.loc[:,_column] > float(list_aux[q-1])) & (df.loc[:,_column] <= float(list_aux[q]))].index
                limit = str(list_aux[q-1]) + ' a ' + str(list_aux[q])
            else:
                location = df[(df.loc[:,_column] <= float(list_aux[q]))].index
                limit = '<=' + str(list_aux[q])
                
            _many = len(location)  
            
            # Target = 1
            _1 = sum(df.loc[location,target])
            _p1 = _1/_t1
            
            # Target = 0
            _0 = _many - _1
            _p0 = _0/_t0
            
            # Relative risk
            if _p1 == 0 or _p0 == 0:
                _RR = 1
            else:
                _RR = _p1/_p0
            
            # Weight of evidence
            _woe = np.log(_RR)
            
            # Information value
            _iv = round(_woe*(_p1-_p0),2)
            
            # Information value - total
            _tiv = _tiv+_iv
                    
            
            dframe = pd.DataFrame({'variable': _column , 'limit':limit , '0': _p0 , '1': _p1, 'RR':_RR, 'WoE': _woe , 'IV':  _iv}
                                  , index = [ _column])  
            
            df_woe_iv = pd.concat([df_woe_iv, dframe], ignore_index=True)
            
        dframe = pd.DataFrame({'variable': _column ,'limit': ' ' , '0': 1 , '1': 1, 'RR': 1 , 'WoE': 0 , 'IV':  _tiv}
                                  , index =[ _column])
         
        df_woe_iv = pd.concat([df_woe_iv, dframe], ignore_index=True)
            
    return df_woe_iv

In [18]:
pd.set_option('display.max_rows', None)

In [19]:
Woe_IV_cont(df, continuas, 'ocorrencia')

,variable,limit,0,1,RR,WoE,IV
0,vintequatrohoras,<=[-11.51292546],0.655189,0.382151,0.583269,-0.539107,0.15
1,vintequatrohoras,[-11.51292546] a [-0.91629073],0.057257,0.033181,0.579506,-0.545579,0.01
2,vintequatrohoras,[-0.91629073] a [1.02961942],0.089525,0.091533,1.022428,0.022181,0.00
3,vintequatrohoras,[1.02961942] a [2.4510051],0.098115,0.123570,1.259445,0.230671,0.01
4,vintequatrohoras,,1.000000,1.000000,1.000000,0.000000,0.17
5,Altitude_numerica,<=[3.59105736],0.100158,0.108696,1.085244,0.081805,0.00
6,Altitude_numerica,[3.59105736] a [3.93789283],0.099830,0.154462,1.547254,0.436482,0.02
7,Altitude_numerica,[3.93789283] a [4.24718513],0.100149,0.155606,1.553753,0.440673,0.02
8,Altitude_numerica,[4.24718513] a [4.47266383],0.099833,0.138444,1.386755,0.326967,0.01
9,Altitude_numerica,[4.47266383] a [4.61568794],0.100160,0.098398,0.982411,-0.017745,0.00
10,Altitude_numerica,[4.61568794] a [4.7457557],0.099840,0.101831,1.019937,0.019741,0.00
11,Altitude_numerica,[4.7457557] a [4.86119879],0.100156,0.118993,1.188080,0.172339,0.00
12,Altitude_numerica,[4.86119879] a [5.00438027],0.099844,0.080092,0.802164,-0.220442,0.00
13,Altitude_numerica,[5.00438027] a [5.26750246],0.100170,0.043478,0.434043,-0.834613,0.05
14,Altitude_numerica,,1.000000,1.000000,1.000000,0.000000,0.10
15,Declividade_numerica,<=[2.44680636],0.100162,0.089245,0.891009,-0.115401,0.00
16,Declividade_numerica,[2.44680636] a [2.79351819],0.099839,0.106407,1.065787,0.063713,0.00
17,Declividade_numerica,[2.79351819] a [3.01053368],0.100152,0.136156,1.359483,0.307104,0.01
18,Declividade_numerica,[3.01053368] a [3.17893567],0.099839,0.107551,1.077249,0.074411,0.00
19,Declividade_numerica,[3.17893567] a [3.33383653],0.100155,0.123570,1.233786,0.210088,0.00
20,Declividade_numerica,[3.33383653] a [3.4928588],0.099835,0.128146,1.283582,0.249655,0.01
21,Declividade_numerica,[3.4928588] a [3.63558672],0.100156,0.115561,1.153801,0.143061,0.00
22,Declividade_numerica,[3.63558672] a [3.77441652],0.099839,0.109840,1.100174,0.095469,0.00
23,Declividade_numerica,[3.77441652] a [3.96724413],0.100166,0.067506,0.673940,-0.394615,0.01
24,Declividade_numerica,,1.000000,1.000000,1.000000,0.000000,0.03
25,graurisc,<=[-11.51292546],0.956641,0.840961,0.879077,-0.128883,0.01
26,graurisc,,1.000000,1.000000,1.000000,0.000000,0.01
27,lon_ocr,<=[0.18431247],0.100156,0.120137,1.199506,0.181910,0.00
28,lon_ocr,[0.18431247] a [0.25339061],0.099823,0.191076,1.914147,0.649272,0.06
29,lon_ocr,[0.25339061] a [0.31128416],0.100145,0.173913,1.736609,0.551935,0.04
30,lon_ocr,[0.31128416] a [0.37294019],0.099814,0.235698,2.361368,0.859241,0.12
31,lon_ocr,[0.37294019] a [0.43932087],0.100152,0.139588,1.393765,0.332009,0.01
32,lon_ocr,[0.43932087] a [0.50298714],0.099841,0.097254,0.974089,-0.026253,0.00
33,lon_ocr,[0.50298714] a [0.58087782],0.100176,0.014874,0.148480,-1.907305,0.16
34,lon_ocr,[0.58087782] a [0.66030473],0.099858,0.010297,0.103121,-2.271849,0.20
35,lon_ocr,[0.66030473] a [0.7604111],0.100177,0.008009,0.079950,-2.526357,0.23
36,lon_ocr,,1.000000,1.000000,1.000000,0.000000,0.82
37,lat_ocr,<=[0.39305933],0.100176,0.012586,0.125636,-2.074363,0.18
38,lat_ocr,[0.39305933] a [0.47550525],0.099849,0.054920,0.550028,-0.597785,0.03
39,lat_ocr,[0.47550525] a [0.54356951],0.100174,0.024027,0.239857,-1.427714,0.11
40,lat_ocr,[0.54356951] a [0.60410495],0.099849,0.053776,0.538568,-0.618841,0.03
41,lat_ocr,[0.60410495] a [0.65108272],0.100162,0.088101,0.879583,-0.128307,0.00
42,lat_ocr,[0.65108272] a [0.70027102],0.099834,0.131579,1.317973,0.276095,0.01
43,lat_ocr,[0.70027102] a [0.7553942],0.100161,0.091533,0.913859,-0.090079,0.00
44,lat_ocr,[0.7553942] a [0.81020602],0.099839,0.109840,1.100174,0.095469,0.00
45,lat_ocr,[0.81020602] a [0.88043193],0.100144,0.179634,1.793755,0.584311,0.05
46,lat_ocr,,1.000000,1.000000,1.000000,0.000000,0.41
47,Orientacao_numerica,<=[0.16600524],0.100158,0.109840,1.096670,0.092278,0.00
48,Orientacao_numerica,[0.16600524] a [0.31268646],0.099840,0.102975,1.031400,0.030917,0.00
49,Orientacao_numerica,[0.31268646] a [0.39592731],0.100163,0.082380,0.822458,-0.195457,0.00
50,Orientacao_numerica,[0.39592731] a [0.46194451],0.099839,0.105263,1.054324,0.052900,0.00
51,Orientacao_numerica,[0.46194451] a [0.53591799],0.100161,0.091533,0.913859,-0.090079,0.00
52,Orientacao_numerica,[0.53591799] a [0.66614625],0.099835,0.129291,1.295046,0.258546,0.01
53,Orientacao_numerica,[0.66614625] a [0.78665119],0.100156,0.120137,1.199506,0.181910,0.00
54,Orientacao_numerica,[0.78665119] a [0.86589271],0.099845,0.078947,0.790703,-0.234833,0.00
55,Orientacao_numerica,[0.86589271] a [0.92434595],0.100165,0.070938,0.708212,-0.345011,0.01
56,Orientacao_numerica,,1.000000,1.000000,1.000000,0.000000,0.02
57,Curv_Vertical_numerica,<=[0.2551465],0.100148,0.161327,1.610894,0.476790,0.03
58,Curv_Vertical_numerica,[0.2551465] a [0.29885269],0.099840,0.102975,1.031400,0.030917,0.00
59,Curv_Vertical_numerica,[0.29885269] a [0.32985031],0.100160,0.098398,0.982411,-0.017745,0.00
60,Curv_Vertical_numerica,[0.32985031] a [0.35524518],0.099844,0.082380,0.825087,-0.192267,0.00
61,Curv_Vertical_numerica,[0.35524518] a [0.38062896],0.100161,0.092677,0.925284,-0.077654,0.00
62,Curv_Vertical_numerica,[0.38062896] a [0.40557596],0.099842,0.093822,0.939703,-0.062192,0.00
63,Curv_Vertical_numerica,[0.40557596] a [0.43773977],0.100158,0.108696,1.085244,0.081805,0.00
64,Curv_Vertical_numerica,[0.43773977] a [0.4867918],0.099842,0.093822,0.939703,-0.062192,0.00
65,Curv_Vertical_numerica,[0.4867918] a [0.56723388],0.100160,0.097254,0.970986,-0.029443,0.00
66,Curv_Vertical_numerica,,1.000000,1.000000,1.000000,0.000000,0.03
67,Curv_Horizontal_numerica,<=[0.36705803],0.100152,0.139588,1.393765,0.332009,0.01
68,Curv_Horizontal_numerica,[0.36705803] a [0.42822954],0.099839,0.106407,1.065787,0.063713,0.00
69,Curv_Horizontal_numerica,[0.42822954] a [0.45792596],0.100163,0.082380,0.822458,-0.195457,0.00
70,Curv_Horizontal_numerica,[0.45792596] a [0.47598292],0.099839,0.107551,1.077249,0.074411,0.00
71,Curv_Horizontal_numerica,[0.47598292] a [0.48922654],0.100162,0.084668,0.845308,-0.168054,0.00
72,Curv_Horizontal_numerica,[0.48922654] a [0.50316847],0.099839,0.109840,1.100174,0.095469,0.00
73,Curv_Horizontal_numerica,[0.50316847] a [0.52101474],0.100162,0.088101,0.879583,-0.128307,0.00
74,Curv_Horizontal_numerica,[0.52101474] a [0.54682165],0.099847,0.066362,0.664632,-0.408521,0.01
75,Curv_Horizontal_numerica,[0.54682165] a [0.59882739],0.100157,0.113272,1.130948,0.123056,0.00
76,Curv_Horizontal_numerica,,1.000000,1.000000,1.000000,0.000000,0.02
77,Relevo_sombreado_numerico,<=[0.00565102],0.100173,0.029748,0.296969,-1.214129,0.09
78,Relevo_sombreado_numerico,[0.00565102] a [0.16866747],0.099843,0.088101,0.882394,-0.125117,0.00
79,Relevo_sombreado_numerico,[0.16866747] a [0.35614481],0.100151,0.146453,1.462330,0.380031,0.02
80,Relevo_sombreado_numerico,[0.35614481] a [0.5192388],0.099830,0.154462,1.547254,0.436482,0.02
81,Relevo_sombreado_numerico,[0.5192388] a [0.65796321],0.100157,0.112128,1.119522,0.112902,0.00
82,Relevo_sombreado_numerico,[0.65796321] a [0.75599202],0.099844,0.081236,0.813625,-0.206255,0.00
83,Relevo_sombreado_numerico,[0.75599202] a [0.83617807],0.100163,0.081236,0.811034,-0.209446,0.00
84,Relevo_sombreado_numerico,[0.83617807] a [0.90046769],0.099844,0.080092,0.802164,-0.220442,0.00
85,Relevo_sombreado_numerico,[0.90046769] a [0.95272173],0.100162,0.088101,0.879583,-0.128307,0.00
86,Relevo_sombreado_numerico,,1.000000,1.000000,1.000000,0.000000,0.13